### ISSUE TITLE
Icon überarbeiten

### ISSUE THREAD

**Issue by lukasklein** [datacake/node-red-nodes#7]
Bei den Stock-Node-RED-Nodes sind die Icons weiss mit transparentem Hintergrund. Das Datacake Icon hat momentan einen schwarzen Hintergrund mit transparentem Vordergrund.
Das sollten wir angleichen.

@clebuchegger bekommst du das hin oder brauchst du das SVG o.ä.?

**Comment by clebuchegger** [comment]
wenns ein SVG gibt, bitte hier einfach reinlegen thx

**Comment by lukasklein** [comment]
[D-Initiale.svg.zip](https://github.com/datacake/node-red-nodes/files/3954067/D-Initiale.svg.zip)
